### ISSUE TITLE
Black screen SKACroppedMiniMap

### ISSUE THREAD

**Issue by TimmNL** [SpriteKitAlliance/SKATMXParser#18]
I've been working with SKAToolKit for the first time now, and so far it has been working the way it has been shown in the example.
Right now I got a problem with the SKACroppedMiniMap since it's showing a black screen.
I've got the following code:

```
class GameScene: SKScene, SKPhysicsContactDelegate {
    override func didMoveToView(view: SKView) {
        tileMap = SKATiledMap(mapName: "tilemap");
        tileMap.name = "tileMap";
        tileMap.zPosition = 0;

        self.addChild(tileMap);

       //creating an interface with my interface class (nothing special)
       self.interface = Interface(startX: -(Int(screenSize.width/2)+227), startY: -(Int(screenSize.height/2)+128), size: CGSize(width: screenSize.width-57, height: screenSize.height-32));
        self.interface?.zPosition = 10;
        self.interface?.name = "interface";
        self.addChild(interface!);

        miniMap = SKAMiniMap(map: tileMap, withWidth: 1150);
        miniMap.position = CGPoint(x: self.size.width - (miniMap.size.width/2),
        y: self.size.height - (miniMap.size.height/2));
        //miniMap.autoFollowNode = player;

        interface?.addChild(miniMap);
    }
}
```

It is in Swift, but I don't really think that could be the problem.

Thanks in advance.

**Comment by TimmNL** [comment]
The same with the normal minimap btw

**Comment by ghost** [comment]
Can you log out the size of your map plz? Not sure how it is in swift but would be 

`NSLog(@"mapSize: %@", NSStringFromCGRect(tileMap.calculateAccumulatedFrame));`

Guessing it will be too big. There is a limit to the max size it will allow and I added it to the header file but I guess I didn't get it added to the ReadMe.

`````` /**
 map must be part of a scene with a view 
 map size max 4096 on newer devices and 2048 max on older devices
 */
- (id)initWithMap:(SKNode *)map withWidth:(NSInteger)width;```
``````

**Comment by TimmNL** [comment]
The output is as followed:
{{0, 0}, {2112, 2112}}
I'm running the app on an iPhone 5, so I'd think it should work with a bigger map.
It also doesn't work with a 2048 map, but it does with a much smaller map.
Maybe something to look into?

**Comment by TimmNL** [comment]
Never mind, I screwed it up with the resizing of the map.
It was the map size after all.

**Comment by ghost** [comment]
Glad you got it figured out. Also note that when you init the mini map there is a limitation on the size but if you create the mini map before you resize the map bigger in theory you won't have any issues. Best of luck on your game! I am also looking into behind the scene options to get around the texture size limitation for initial creation of the mini map texture too.

**Comment by TimmNL** [comment]
I've got the cropped minimap working, but the player, which is shown in the mini map, doesn't move.
It also doesn't show any other added sprites during runtime.
Is this supposed to happen?
If so, maybe a nice feature for in the future :)

**Comment by ghost** [comment]
Yes that is suppose to happen. What it does is create a texture of the map when you create the mini map. I recommend creating it before you add the player but after you add any elements at run time. If stuff isn't added when you create the mini map it won't be there. This is do to performance issues. Creating a texture at that size every update loop would be very expensive on the processor. I could be wrong but typically you don't see moving platforms on a mini map. I can see an issue if you are looking for enemies and such. I will keep that in mind and continue to look for improvements. Thanks for the feedback.
