### ISSUE TITLE
ios 9 devices images from atlas not working properly

### ISSUE THREAD

**Issue by Abhijit-Kayande** [SpriteKitAlliance/SKATMXParser#19]
I have a tile map using collection of images from .atlas folder. It is working good on ios8 using SKATiledMap but on ios9 real device the map is not showing properly. The map looks broken, random tiles here and there.

**Comment by ghost** [comment]
Can you share a screen grab of it working on iOS 8 and not on iOS 9 so I can try to troubleshoot it?

**Comment by Abhijit-Kayande** [comment]
Ya I will post image soon. cant do it now because of some busy schedule.
For now I have found a workaround, If I move images out of the atlas folder then map shows perfect. The problem is only with the ios 9 atlas folder on my iPhone 6. ios 9 simulator also shows map correctly.

**Comment by ghost** [comment]
Ok I pushed a fix for it. iOS 9 does not like it if you use the .png extension. You will want to move those images back into the atlas folder to get better performance. Please let me know if you run into any more issues.

**Comment by Abhijit-Kayande** [comment]
Ok thanks, I will try it. Right now first version of my game is in waiting for review status. I will try to implement in the next update ;). Thanks again. :)
