### ISSUE TITLE
Map scaling

### ISSUE THREAD

**Issue by NI92** [SpriteKitAlliance/SKATMXParser#24]
When you currently scale the world in or out the camera perspective gets messed up: moves to the left & down. The more you scale the more left & down it goes.

This is because of the way the algorithm is written to make sure nothing outside the map is shown: so when the character comes to a border the camera doesn’t keep following him & shows the nothingness.

Easy fix is to have an alternate option for camera following: no algorithms during camera positioning calculation.

The nothingness outside the map will be visible but scaling won't be a problem anymore.

This way, one won't require new art assets, but simply will be able to scale the world by 2 while making sure texture filtering is set to nearest.

**Comment by ghost** [comment]
The map wasn't meant to be scaled so I see how this would mess up the auto follow logic. I will see if there is a work around. Also I suspect this will mess up the index for point logic too as the tileWidth/tileHeight will not be accurate after scaling. In the short term if you are targeting iOS 9 or higher I believe they added an SKCameraNode which might be worth looking into. I will close this as it isn't an issue but will look into this as a future feature.
