### ISSUE TITLE
Add collectibles "coins, keys, diamonds etc" in code

### ISSUE THREAD

**Issue by bigbadbrad08** [SpriteKitAlliance/SKATMXParser#26]
hi first of all, nice code SKAToolKit, i would like to know how can i add collectibles function to my code, and some sort of end point, to finish a level... Many thanks for this!!

**Comment by ghost** [comment]
You would want to utilize object layers and objects in Tiled. If you set a property on an object to something like "gem" : "blueGem"

```
    SKAObjectLayer *layer = self.map.objectLayers.firstObject;

    for (SKAObject *skaObject in layer.objects){
        if (skaObject.properties[@"gem"]){
            //create your gem
            SKSpriteNode *gemSprite = [SKSpriteNode spriteNodeWithImageNamed:skaObject.properties[@"gem"]];
            gemSprite.position = CGPointMake(skaObject.x, skaObject.y);
            gemSprite.zPosition = 10;
            [self.map addChild:gemSprite];
        }
    }
```

**Comment by bigbadbrad08** [comment]
can you explain a bit more? im relative new to swift, im using Swift 2 Xcode 7.2 i already create a new object layer "gem" on Tiled, and added some gems to the map but when im adding the code you give me im having some problems

**Comment by ghost** [comment]
Feel free to email me at skyler@skymistdevelopment.com. to continue this conversation. You say your using swift but you are using the Objective-C version of SKATiledMap and I provided Objective-C code for what appears to be a Swift project =) If you email me more details of what you tried perhaps I can help more.

**Comment by bigbadbrad08** [comment]
oh many thanks im gonna email u right now THANKS!!

**Comment by bigbadbrad08** [comment]
this is what happen when i add the code, im super new to swift seriously
hhahahaa

2016-03-22 11:39 GMT-04:30 Skyler Lauren notifications@github.com:

**Comment by bigbadbrad08** [comment]
im using a swift version of SKAToolKit

2016-03-22 11:56 GMT-04:30 carlos avila avilacef@gmail.com:
