### ISSUE TITLE
Margin and Spacing are missing on TMX load

### ISSUE THREAD

**Issue by ghost** [SpriteKitAlliance/SKATMXParser#3]
Margin and Spacing are missing in the dictionary when loading from TMX file

![screenshot 2015-06-21 10 16 41](https://cloud.githubusercontent.com/assets/10824143/8272188/bec2415e-17fe-11e5-85a9-2253e484ee9a.png)
![screenshot 2015-06-21 10 17 07](https://cloud.githubusercontent.com/assets/10824143/8272189/bec2dd4e-17fe-11e5-8a09-3b0adc9786c9.png)

**Comment by benkane** [comment]
@Urthstripe29 The margin and spacing are in the dictionary for me. They are a part of each tileset. Can you reproduce a dictionary without them in it?

**Comment by benkane** [comment]
Added some margin and spacing to the tilesets in SampleMap0 and they are working. I'll look into this more if you can provide a sample project where it's not working.

**Comment by ghost** [comment]
Issue wasn't actually spacing. the width/height was flipped. Fixed on development branch.
